id: P010485
initial_creation_type: ocr
source_metadata:
  id: bdr:W20204
  title: དགེ་འདུན་ཆོས་འཕེལ
  author: ''
  volumes:
    a7a043f57ab04f97a448d10252644957:
      image_group_id: I5682
      title: ''
      volume_number: 1
      total_pages: 152
      base_file: v001.txt
