id: I0120B100
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T06:31:47+00:00'
last_modified: '2022-06-08T13:56:56.834306+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20204
  title: དགེ་འདུན་ཆོས་འཕེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    17A1:
      image_group_id: I5682
      title: ''
      total_pages: 152
      order: 1
      base_file: 17A1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
